from enum import Enum


class ErrorCode(str, Enum):
    # Validation & File Errors
    INVALID_PDF_FORMAT = "INVALID_PDF_FORMAT"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    EXCEEDS_PAGE_LIMIT = "EXCEEDS_PAGE_LIMIT"
    PDF_CORRUPTED = "PDF_CORRUPTED"
    PDF_ENCRYPTED = "PDF_ENCRYPTED"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    INVALID_FILENAME = "INVALID_FILENAME"

    # Job Errors
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    JOB_ALREADY_RUNNING = "JOB_ALREADY_RUNNING"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    JOB_CANCELLED = "JOB_CANCELLED"
    MAX_RETRIES_EXCEEDED = "MAX_RETRIES_EXCEEDED"

    # Storage Errors
    STORAGE_ERROR = "STORAGE_ERROR"
    S3_UPLOAD_ERROR = "S3_UPLOAD_ERROR"
    S3_DOWNLOAD_ERROR = "S3_DOWNLOAD_ERROR"
    S3_CONFIG_ERROR = "S3_CONFIG_ERROR"

    # OCR / Groq Errors
    GROQ_API_ERROR = "GROQ_API_ERROR"
    GROQ_RATE_LIMITED = "GROQ_RATE_LIMITED"
    GROQ_TIMEOUT = "GROQ_TIMEOUT"
    GROQ_AUTH_ERROR = "GROQ_AUTH_ERROR"
    OCR_DISABLED = "OCR_DISABLED"
    OCR_FAILED = "OCR_FAILED"

    # Auth Errors
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"

    # Generic & System Errors
    DATABASE_ERROR = "DATABASE_ERROR"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
